# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Amigo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Amigo
pod 'GoogleMaps'

  target 'AmigoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AmigoUITests' do
    # Pods for testing
  end

end
